- name: Update repositories cache and install nfs-common package
  apt:
    name: nfs-common
    update_cache: yes
- name: Create shared folder
  file:
    path={{ nfs_path }}
    state: directory
    owner: {{ user_name }}
    group: {{ user_name }}
    mode: 777
- name: Mount NFS Device
  mount:
    name: {{ nfs_path }}
    src: {{ server_ip}}:{{ nfs_path }}
    fstype: nfs
    opts: rw
    state: present
