---
- find:
    paths: /usr/local/
    patterns: "*.tgz"
  register: find_results

- file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ find_results['files'] }}"

- get_url: url={{spark_version}} dest=/tmp/spark-{{spark_version}}-bin-hadoop2.7.tgz force=no
  register: result
  until: result|success
  retries: 3
  delay: 2

- name: Decompress it
  unarchive: src=/tmp/spark-{{spark_version}}-bin-hadoop2.7.tgz dest=/usr/local/ copy=no creates=/opt/spark-{{spark_version}}-bin-hadoop2.7 copy=no

- name: Create symbolic link to spark
  file: src=/usr/local/spark-{{spark_version}}-bin-hadoop2.7 dest=/usr/local/spark state=link

- name: update PATH environment variable
  copy: dest=/etc/profile.d/spark.sh content="export PATH=$PATH:/usr/local/spark/bin\nexport SPARK_HOME=/usr/local/spark"
